package plugin

import (
	"github.com/mimokpl/miwin-toolkit/protoc-gen-common/codegen"
	"github.com/mimokpl/miwin-toolkit/protoc-gen-common/httprule"
	"github.com/mimokpl/miwin-toolkit/protoc-gen-common/protowalk"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type packageGenerator struct {
	pkg   protoreflect.FullName
	files []protoreflect.FileDescriptor
}

func (p packageGenerator) Generate(f *codegen.File) error {
	p.generateHeader(f)
	hasServices := p.hasServices()

	// Conditionally add imports only when the package has services.
	if hasServices {
		f.P("import 'dart:async';")
		f.P("import 'dart:convert';")
	}
	// 二进制 proto 编解码成员（writeToBuffer/fromBuffer）所需
	f.P("import 'dart:typed_data';")
	f.P("import '", transportImportPath(p.pkg), "';")
	f.P("import '", protoWireImportPath(p.pkg), "';")
	f.P()

	// defaultHost constant (only if there are services and a host is set).
	defaultHost := httprule.FirstDefaultHost(p.files, Warn)
	if hasServices && defaultHost != "" {
		f.P("const defaultHost = ", dartString(defaultHost), ";")
		f.P()
	}

	var walkErr error
	var services []protoreflect.ServiceDescriptor
	protowalk.WalkFiles(p.files, func(desc protoreflect.Descriptor) bool {
		if wkt, ok := WellKnownType(desc); ok {
			f.P(wkt.TypeDeclaration())
			return false
		}
		switch v := desc.(type) {
		case protoreflect.MessageDescriptor:
			if v.IsMapEntry() {
				return false
			}
			messageGenerator{pkg: p.pkg, message: v}.Generate(f)
		case protoreflect.EnumDescriptor:
			enumGenerator{pkg: p.pkg, enum: v}.Generate(f)
		case protoreflect.ServiceDescriptor:
			services = append(services, v)
			if err := (serviceGenerator{
				pkg:     p.pkg,
				service: v,
			}).Generate(f); err != nil {
				walkErr = err
				return false
			}
		}
		return true
	})
	if walkErr != nil {
		return walkErr
	}
	// Generate the unified ApiClient after all individual service clients.
	generateApiClient(f, services)
	return nil
}

func (p packageGenerator) generateHeader(f *codegen.File) {
	f.P("// Code generated by protoc-gen-dart-http. DO NOT EDIT.")
	f.P()
	f.P("// ignore_for_file: unused_import, unnecessary_cast, avoid_print, non_constant_identifier_names, avoid_equals_and_hash_code_on_mutable_classes")
	f.P()
}

// hasServices returns true if any file in the package declares a service.
func (p packageGenerator) hasServices() bool {
	for _, file := range p.files {
		if file.Services().Len() > 0 {
			return true
		}
	}
	return false
}
