package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"
	"text/template"

	pgs "github.com/lyft/protoc-gen-star/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestExternalTemplateLoading tests loading templates from external files.
// 全部产物落在 t.TempDir(),不再原地覆写仓库文件;protoc 不在 PATH
// 时跳过。
func TestExternalTemplateLoading(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in short mode")
	}
	if _, err := exec.LookPath("protoc"); err != nil {
		t.Skip("protoc not found in PATH; skipping external template test")
	}

	currentDir, err := os.Getwd()
	require.NoError(t, err)

	// 把被测插件编译进临时目录。
	pluginPath := filepath.Join(t.TempDir(), "protoc-gen-redact")
	if runtime.GOOS == "windows" {
		pluginPath += ".exe"
	}
	buildCmd := exec.Command("go", "build", "-o", pluginPath, ".")
	buildCmd.Env = append(os.Environ(), "GOWORK=off")
	buildOutput, err := buildCmd.CombinedOutput()
	require.NoError(t, err, "Should build protoc-gen-redact plugin: %s", string(buildOutput))

	templatePath := filepath.Join(currentDir, "examples", "custom-template.tmpl")
	require.FileExists(t, templatePath, "Example template should exist")

	protoFile := filepath.Join(currentDir, "testdata", "integration", "test.proto")

	runProtoc := func(outDir string, templateOpt string) ([]byte, error) {
		cmd := exec.Command("protoc",
			"--experimental_allow_proto3_optional",
			"--plugin=protoc-gen-redact="+pluginPath,
			"--redact_out="+outDir,
			"--redact_opt="+templateOpt+",paths=source_relative",
			"-I="+currentDir,
			protoFile,
		)
		return cmd.CombinedOutput()
	}

	t.Run("use_external_template", func(t *testing.T) {
		outDir := t.TempDir()
		output, err := runProtoc(outDir, "template_file="+templatePath)
		require.NoError(t, err, "Should generate code with external template: %s", string(output))

		// 产物落在临时目录里。
		redactFile := filepath.Join(outDir, "testdata", "integration", "test.pb.redact.go")
		require.FileExists(t, redactFile, "Generated redaction file should exist in the temp dir")

		content, err := os.ReadFile(redactFile)
		require.NoError(t, err)

		contentStr := string(content)
		assert.Contains(t, contentStr, "package testdata", "Should have correct package")
		assert.Contains(t, contentStr, "Code generated by protoc-gen-redact", "Should have generated comment")
		assert.Contains(t, contentStr, "func (x *TestMessage) Redact()", "Should have Redact method")
	})

	t.Run("nonexistent_template_file", func(t *testing.T) {
		outDir := t.TempDir()
		output, err := runProtoc(outDir, "template_file=/nonexistent/template.tmpl")
		require.Error(t, err, "Should fail with nonexistent template")
		assert.Contains(t, string(output), "file does not exist", "Should report file not found")
	})

	t.Run("invalid_template_syntax", func(t *testing.T) {
		invalidTemplate := filepath.Join(t.TempDir(), "invalid.tmpl")
		err := os.WriteFile(invalidTemplate, []byte("{{ invalid syntax"), 0o644)
		require.NoError(t, err)

		outDir := t.TempDir()
		output, err := runProtoc(outDir, "template_file="+invalidTemplate)
		require.Error(t, err, "Should fail with invalid template")
		assert.Contains(t, string(output), "failed to parse template", "Should report parse error")
	})

	t.Run("template_too_large", func(t *testing.T) {
		largeTemplate := filepath.Join(t.TempDir(), "large.tmpl")
		largeContent := make([]byte, 11*1024*1024)
		for i := range largeContent {
			largeContent[i] = 'a'
		}
		err := os.WriteFile(largeTemplate, largeContent, 0o644)
		require.NoError(t, err)

		outDir := t.TempDir()
		output, err := runProtoc(outDir, "template_file="+largeTemplate)
		require.Error(t, err, "Should fail with oversized template")
		assert.Contains(t, string(output), "too large", "Should report size error")
	})

	t.Run("relative_path_template", func(t *testing.T) {
		// 模板路径保持相对形式(相对进程工作目录解析),输出仍进临时目录。
		outDir := t.TempDir()
		cmd := exec.Command("protoc",
			"--experimental_allow_proto3_optional",
			"--plugin=protoc-gen-redact="+pluginPath,
			"--redact_out="+outDir,
			"--redact_opt=template_file=./examples/custom-template.tmpl,paths=source_relative",
			"-I="+currentDir,
			protoFile,
		)
		cmd.Dir = currentDir

		output, err := cmd.CombinedOutput()
		require.NoError(t, err, "Should work with relative paths: %s", string(output))
	})
}

// TestTemplateParameterValidation tests template parameter validation
func TestTemplateParameterValidation(t *testing.T) {
	m := &Module{ModuleBase: &pgs.ModuleBase{}}

	tests := []struct {
		name        string
		setupFunc   func() string // returns template path
		shouldError bool
		errorMsg    string
	}{
		{
			name: "empty_path",
			setupFunc: func() string {
				return ""
			},
			shouldError: true,
			errorMsg:    "empty",
		},
		{
			name: "directory_not_file",
			setupFunc: func() string {
				tmpDir := t.TempDir()
				return tmpDir
			},
			shouldError: true,
			errorMsg:    "not a regular file",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			templatePath := tt.setupFunc()

			tpl := &template.Template{}
			_, err := m.loadTemplateFromFile(tpl, templatePath)

			if tt.shouldError {
				require.Error(t, err)
				if tt.errorMsg != "" {
					assert.Contains(t, err.Error(), tt.errorMsg)
				}
			} else {
				require.NoError(t, err)
			}
		})
	}
}
