package main

import (
	"fmt"
	"net/http"
	"os"
	"regexp"
	"strings"

	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/mimokpl/miwin-toolkit/protoc-gen-common/httprule"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	contextPackage   = protogen.GoImportPath("context")
	httpPackage      = protogen.GoImportPath("net/http")
	bindingPackage   = protogen.GoImportPath("github.com/mimokpl/miwin-plugins/transport/http/binding")
	httpBodyFullName = protoreflect.FullName("google.api.HttpBody")
)

var methodSets = make(map[string]int)

// generateFile 读取 proto 文件并生成对应的 _http.pb.go 文件，其中包含 HTTP 服务端接口与路由处理代码。
// 若文件无 Service，或 omitempty 为真且无 google.api.http 注解，则跳过生成。
//
// generateFile reads a proto file and produces the corresponding _http.pb.go file, containing
// the HTTP server interface and route handler code. Generation is skipped when the file has no
// service, or when omitempty is true and no google.api.http annotation is present.
//
// generateFile は proto ファイルを読み込み、HTTP サーバーインターフェースとルートハンドラコードを含む
// _http.pb.go ファイルを生成します。ファイルにサービスがない場合、または omitempty が true で
// google.api.http アノテーションが存在しない場合は生成をスキップします。
func generateFile(gen *protogen.Plugin, file *protogen.File, omitempty bool, omitemptyPrefix string) *protogen.GeneratedFile {
	if len(file.Services) == 0 || (omitempty && !hasHTTPRule(file.Services)) {
		return nil
	}
	filename := file.GeneratedFilenamePrefix + "_http.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-http. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-http %s", release))
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	generateFileContent(gen, file, g, omitempty, omitemptyPrefix)
	return g
}

// generateFileContent 生成除 package 声明以外的 HTTP 服务端代码内容（服务接口、注册函数与各方法处理器）。
//
// generateFileContent generates the HTTP server code content excluding the package statement
// (server interface, registration function and per-method handlers).
//
// generateFileContent は package 宣言を除く HTTP サーバーコード（サーバーインターフェース、登録関数、
// 各メソッドハンドラ）を生成します。
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, omitempty bool, omitemptyPrefix string) {
	if len(file.Services) == 0 {
		return
	}
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the miwin package it is being compiled against.")
	g.P("var _ = new(", contextPackage.Ident("Context"), ")")
	g.P("var _ ", httpPackage.Ident("ResponseWriter"))
	g.P("var _ = ", bindingPackage.Ident("WriteResponse"))
	g.P()

	for _, service := range file.Services {
		genService(gen, file, g, service, omitempty, omitemptyPrefix)
	}
}

func genService(_ *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service, omitempty bool, omitemptyPrefix string) {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	// HTTP Server.
	sd := &serviceDesc{
		ServiceType: service.GoName,
		ServiceName: string(service.Desc.FullName()),
		Metadata:    file.Desc.Path(),
	}
	for _, method := range service.Methods {
		if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
			if !isHttpBodyStreamMethod(method) {
				_, _ = fmt.Fprintf(os.Stderr, "\u001B[33mWARN\u001B[m: skipping streaming method %s (only google.api.HttpBody streams are generated over HTTP; other element types need SSE/WebSocket transports)\n", method.GoName)
				continue
			}
			// HttpBody 流式方法继续走注解处理，handler 按流式形态生成。
		}
		rule, ok := httprule.Get(method.Desc)
		if ok {
			for _, bind := range rule.AdditionalBindings {
				sd.Methods = append(sd.Methods, buildHTTPRule(g, service, method, bind))
			}
			sd.Methods = append(sd.Methods, buildHTTPRule(g, service, method, rule))
		} else if !omitempty && !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer() {
			path := fmt.Sprintf("%s/%s/%s", omitemptyPrefix, service.Desc.FullName(), method.Desc.Name())
			sd.Methods = append(sd.Methods, buildMethodDesc(g, method, http.MethodPost, path, nil))
		}
	}
	if len(sd.Methods) != 0 {
		g.P(sd.execute())
	}
}

func hasHTTPRule(services []*protogen.Service) bool {
	for _, service := range services {
		for _, method := range service.Methods {
			if _, ok := httprule.Get(method.Desc); ok {
				return true
			}
		}
	}
	return false
}

func buildHTTPRule(g *protogen.GeneratedFile, service *protogen.Service, m *protogen.Method, rule *annotations.HttpRule) *methodDesc {
	// 解析与校验统一走共享 httprule:缺 pattern、畸形模板(/**/*、嵌套
	// 或重复变量、尾斜杠等)在此报错终止,不再静默合成默认路由——
	// 与 dart/TS 插件对同一输入的拒绝语义对齐。
	parsed, err := httprule.ParseRule(rule)
	if err != nil {
		fmt.Fprintf(os.Stderr, "\u001B[31mERROR\u001B[m: %s.%s: %v\n", service.Desc.FullName(), m.Desc.Name(), err)
		os.Exit(2)
	}
	method := parsed.Method
	if method == "" {
		method = http.MethodPost
	}
	body := parsed.Body
	responseBody := rule.ResponseBody
	varFieldPaths := parsed.Template.PathVariableFieldPaths()
	routePath := renderRoutePath(parsed.Template)
	md := buildMethodDesc(g, m, method, routePath, varFieldPaths)
	// Client-streaming RPCs are served over WebSocket, whose handshake is always an
	// HTTP GET regardless of the declared verb. Declaring a body for them is legitimate
	// (it identifies the streamed message field), so skip the GET/DELETE body warnings.
	if !m.Desc.IsStreamingClient() {
		if method == http.MethodGet || method == http.MethodDelete {
			if body != "" {
				_, _ = fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: %s %s body should not be declared.\n", method, routePath)
			}
		} else {
			// An undeclared body is only a silent-degradation bug when request fields
			// exist that no path variable binds — those fall back to query parameters.
			// When every field is path-bound (or the request has none), the empty body
			// is the intended contract: opaque-payload endpoints keep the body out of
			// proto binding entirely and consume it as raw bytes.
			if body == "" && !allFieldsPathBound(inputFieldNames(m), varFieldPaths) {
				_, _ = fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: %s %s does not declare a body.\n", method, routePath)
			}
		}
	}
	if m.Desc.IsStreamingClient() {
		// 客户端流式：请求体就是字节流本身，不经 proto 绑定；注解里的
		// body 声明对流式语义无意义，忽略并提示。
		if body != "" {
			_, _ = fmt.Fprintf(os.Stderr, "\u001B[33mWARN\u001B[m: %s %s body declaration ignored for client-streaming method; the request body is the byte stream itself.\n", method, routePath)
		}
		md.HasBody = false
	} else if body == "*" {
		md.HasBody = true
		md.Body = ""
		md.BodyField = "*"
		md.BodyHTTPBody = isHTTPBodyMessage(m.Input.Desc)
	} else if body != "" {
		fd := m.Input.Desc.Fields().ByName(protoreflect.Name(body))
		if fd == nil {
			fmt.Fprintf(
				os.Stderr,
				"\u001B[31mERROR\u001B[m: The corresponding body field '%s' declaration in request message could not be found in '%s'\n",
				body,
				routePath,
			)
			os.Exit(2)
		}
		md.HasBody = true
		md.Body = "." + camelCaseVars(body)
		md.BodyField = body
		md.BodyQueryName = fd.JSONName()
		md.BodyHTTPBody = isHTTPBodyField(fd)
		// A singular message-kind body field can be streamed frame-by-frame for
		// client-streaming RPCs (each frame carries just this field's payload).
		md.BodyMessage = fd.Kind() == protoreflect.MessageKind && !fd.IsList() && !fd.IsMap()
	} else {
		md.HasBody = false
	}
	if responseBody == "*" {
		md.ResponseBody = ""
	} else if responseBody != "" {
		fd := m.Output.Desc.Fields().ByName(protoreflect.Name(responseBody))
		if fd == nil {
			fmt.Fprintf(
				os.Stderr,
				"\u001B[31mERROR\u001B[m: The corresponding response_body field '%s' declaration in response message could not be found in '%s'\n",
				responseBody,
				routePath,
			)
			os.Exit(2)
		}
		md.ResponseBody = "." + camelCaseVars(responseBody)
	}
	return md
}

func buildMethodDesc(g *protogen.GeneratedFile, m *protogen.Method, method, path string, varFieldPaths []httprule.FieldPath) *methodDesc {
	defer func() { methodSets[m.GoName]++ }()

	var pathVarNames []string
	for _, fp := range varFieldPaths {
		fields := m.Input.Desc.Fields()
		for _, field := range fp {
			if strings.TrimSpace(field) == "" {
				continue
			}
			fd := fields.ByName(protoreflect.Name(field))
			if fd == nil {
				fmt.Fprintf(os.Stderr, "\u001B[31mERROR\u001B[m: The corresponding field '%s' declaration in message could not be found in '%s'\n", strings.Join(fp, "."), path)
				os.Exit(2)
			}
			if fd.IsMap() {
				fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: The field in path:'%s' shouldn't be a map.\n", strings.Join(fp, "."))
			} else if fd.IsList() {
				fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: The field in path:'%s' shouldn't be a list.\n", strings.Join(fp, "."))
			} else if fd.Kind() == protoreflect.MessageKind || fd.Kind() == protoreflect.GroupKind {
				fields = fd.Message().Fields()
			}
		}
		pathVarNames = append(pathVarNames, strings.Join(fp, "."))
	}
	comment := m.Comments.Leading.String() + m.Comments.Trailing.String()
	if comment != "" {
		comment = "// " + m.GoName + strings.TrimPrefix(strings.TrimSuffix(comment, "\n"), "//")
	}
	if m.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
		if comment != "" {
			comment += "\n"
		}
		comment += deprecationComment
	}
	return &methodDesc{
		Name:            m.GoName,
		OriginalName:    string(m.Desc.Name()),
		Num:             methodSets[m.GoName],
		Request:         g.QualifiedGoIdent(m.Input.GoIdent),
		Reply:           g.QualifiedGoIdent(m.Output.GoIdent),
		StreamElem:      streamElemGoIdent(g, m),
		Comment:         comment,
		Path:            path,
		Method:          method,
		HasVars:         len(varFieldPaths) > 0,
		PathVarsList:    formatStringSlice(pathVarNames),
		ReplyHTTPBody:   isHTTPBodyMessage(m.Output.Desc),
		ClientStreaming: m.Desc.IsStreamingClient(),
		ServerStreaming: m.Desc.IsStreamingServer(),
	}
}

// isHttpBodyStreamMethod 判定流式方法是否为 HttpBody 流——HTTP 绑定唯一
// 生成的流式形态（下行分块写 + 上行请求体直传）。其他流式元素类型仍被跳过。
func isHttpBodyStreamMethod(m *protogen.Method) bool {
	if m.Desc.IsStreamingClient() && isHTTPBodyMessage(m.Input.Desc) {
		return true
	}
	if m.Desc.IsStreamingServer() && isHTTPBodyMessage(m.Output.Desc) {
		return true
	}
	return false
}

// streamElemGoIdent 返回 HttpBody 流式方法的流式元素限定 Go 类型名；
// 普通方法返回空串。
func streamElemGoIdent(g *protogen.GeneratedFile, m *protogen.Method) string {
	if m.Desc.IsStreamingClient() && isHTTPBodyMessage(m.Input.Desc) {
		return g.QualifiedGoIdent(m.Input.GoIdent)
	}
	if m.Desc.IsStreamingServer() && isHTTPBodyMessage(m.Output.Desc) {
		return g.QualifiedGoIdent(m.Output.GoIdent)
	}
	return ""
}

func isHTTPBodyField(fd protoreflect.FieldDescriptor) bool {
	return fd != nil && fd.Kind() == protoreflect.MessageKind && isHTTPBodyMessage(fd.Message())
}

func isHTTPBodyMessage(md protoreflect.MessageDescriptor) bool {
	return md != nil && md.FullName() == httpBodyFullName
}

// renderRoutePath 从解析后的模板段确定性重建 kratos 路由注册形态。
// 字面量与通配段原样输出;带显式 matcher 的变量段把 {name=matcher}
// 重写为 {name:regex}(matcher 内字面量经 regexp.QuoteMeta 转义),
// 裸变量段保持 {name} 形态。
//
// 共享解析器把裸 {name} 与 {name=*} 统一表示为默认单段匹配(语义
// 等价),二者均渲染为裸形态;替换发生在段重建时的精确跨度上,不再
// 经由第二条按变量名构造的正则——旧路径中该正则未对变量名做
// QuoteMeta 且跳过单字符变量,存在跨变量误替换与漏替换。
func renderRoutePath(tmpl httprule.Template) string {
	var b strings.Builder
	b.WriteString("/")
	for i, seg := range tmpl.Segments {
		if i > 0 {
			b.WriteString("/")
		}
		renderSegment(&b, seg)
	}
	if tmpl.Verb != "" {
		b.WriteString(":")
		b.WriteString(tmpl.Verb)
	}
	return b.String()
}

func renderSegment(b *strings.Builder, seg httprule.Segment) {
	switch seg.Kind {
	case httprule.SegmentKindLiteral:
		b.WriteString(seg.Literal)
	case httprule.SegmentKindMatchSingle:
		b.WriteString("*")
	case httprule.SegmentKindMatchMultiple:
		b.WriteString("**")
	case httprule.SegmentKindVariable:
		v := seg.Variable
		b.WriteString("{")
		b.WriteString(strings.Join(v.FieldPath, "."))
		if isDefaultSingleMatch(v.Segments) {
			// 裸变量或显式 {name=*}:默认单段匹配,保持裸形态。
			b.WriteString("}")
			return
		}
		b.WriteString(":")
		b.WriteString(pathTemplateRegex(renderMatcher(v.Segments)))
		b.WriteString("}")
	}
}

// isDefaultSingleMatch 判定变量 matcher 是否为解析器为裸变量填充的
// 默认单段匹配([MatchSingle] 且无其他段)。
func isDefaultSingleMatch(segs []httprule.Segment) bool {
	return len(segs) == 1 && segs[0].Kind == httprule.SegmentKindMatchSingle
}

// renderMatcher 重建变量 matcher 的原始文本,供 pathTemplateRegex
// 转成路由正则。
func renderMatcher(segs []httprule.Segment) string {
	parts := make([]string, 0, len(segs))
	for _, seg := range segs {
		switch seg.Kind {
		case httprule.SegmentKindLiteral:
			parts = append(parts, seg.Literal)
		case httprule.SegmentKindMatchSingle:
			parts = append(parts, "*")
		case httprule.SegmentKindMatchMultiple:
			parts = append(parts, "**")
		}
	}
	return strings.Join(parts, "/")
}

// inputFieldNames lists the top-level field names of a method's request message.
func inputFieldNames(m *protogen.Method) []string {
	fields := m.Input.Desc.Fields()
	names := make([]string, 0, fields.Len())
	for i := 0; i < fields.Len(); i++ {
		names = append(names, string(fields.Get(i).Name()))
	}
	return names
}

// allFieldsPathBound reports whether every listed request field is consumed
// by a top-level path variable of this template. A field list with no
// entries is vacuously bound: with nothing left that could fall back from
// body to query binding, an undeclared body is a legitimate contract rather
// than a degradation bug. Dotted path variables (e.g. "{foo.bar}")
// deliberately bind no top-level field name, so nested bindings stay on the
// warning side of the check.
func allFieldsPathBound(fieldNames []string, varFieldPaths []httprule.FieldPath) bool {
	for _, name := range fieldNames {
		bound := false
		for _, fp := range varFieldPaths {
			if len(fp) == 1 && fp[0] == name {
				bound = true
				break
			}
		}
		if !bound {
			return false
		}
	}
	return true
}

func pathTemplateRegex(value string) string {
	segs := strings.Split(value, "/")
	for i, seg := range segs {
		switch seg {
		case "*":
			segs[i] = "[^/]+"
		case "**":
			segs[i] = ".*"
		default:
			segs[i] = regexp.QuoteMeta(seg)
		}
	}
	return strings.Join(segs, "/")
}

func camelCaseVars(s string) string {
	subs := strings.Split(s, ".")
	vars := make([]string, 0, len(subs))
	for _, sub := range subs {
		vars = append(vars, camelCase(sub))
	}
	return strings.Join(vars, ".")
}

// camelCase returns the CamelCased name.
// If there is an interior underscore followed by a lower case letter,
// drop the underscore and convert the letter to upper case.
// There is a remote possibility of this rewrite causing a name collision,
// but it's so remote we're prepared to pretend it's nonexistent - since the
// C++ generator lowercase names, it's extremely unlikely to have two fields
// with different capitalization.
// In short, _my_field_name_2 becomes XMyFieldName_2.
func camelCase(s string) string {
	if s == "" {
		return ""
	}
	t := make([]byte, 0, 32)
	i := 0
	if s[0] == '_' {
		// Need a capital letter; drop the '_'.
		t = append(t, 'X')
		i++
	}
	// Invariant: if the next letter is lower case, it must be converted
	// to upper case.
	// That is, we process a word at a time, where words are marked by _ or
	// upper case letter. Digits are treated as words.
	for ; i < len(s); i++ {
		c := s[i]
		if c == '_' && i+1 < len(s) && isASCIILower(s[i+1]) {
			continue // Skip the underscore in s.
		}
		if isASCIIDigit(c) {
			t = append(t, c)
			continue
		}
		// Assume we have a letter now - if not, it's a bogus identifier.
		// The next word is a sequence of characters that must start upper case.
		if isASCIILower(c) {
			c ^= ' ' // Make it a capital letter.
		}
		t = append(t, c) // Guaranteed not lower case.
		// Accept lower case sequence that follows.
		for i+1 < len(s) && isASCIILower(s[i+1]) {
			i++
			t = append(t, s[i])
		}
	}
	return string(t)
}

// Is c an ASCII lower-case letter?
func isASCIILower(c byte) bool {
	return 'a' <= c && c <= 'z'
}

// Is c an ASCII digit?
func isASCIIDigit(c byte) bool {
	return '0' <= c && c <= '9'
}

// formatStringSlice formats a string slice as a Go string slice literal.
// Returns "" (empty) for nil or empty slices.
func formatStringSlice(ss []string) string {
	if len(ss) == 0 {
		return ""
	}
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

const deprecationComment = "// Deprecated: Do not use."
