package plugin

import (
	"github.com/mimokpl/miwin-toolkit/protoc-gen-common/codegen"
	"github.com/mimokpl/miwin-toolkit/protoc-gen-common/httprule"
	"github.com/mimokpl/miwin-toolkit/protoc-gen-common/protowalk"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type packageGenerator struct {
	pkg   protoreflect.FullName
	files []protoreflect.FileDescriptor
}

func (p packageGenerator) Generate(f *codegen.File) error {
	p.generateHeader(f)
	defaultHost := httprule.FirstDefaultHost(p.files, Warn)
	generateTransportInfra(f, defaultHost)
	var walkErr error
	var services []protoreflect.ServiceDescriptor
	protowalk.WalkFiles(p.files, func(desc protoreflect.Descriptor) bool {
		if wkt, ok := WellKnownType(desc); ok {
			f.P(wkt.TypeDeclaration())
			return false
		}
		switch v := desc.(type) {
		case protoreflect.MessageDescriptor:
			if v.IsMapEntry() {
				return false
			}
			messageGenerator{pkg: p.pkg, message: v}.Generate(f)
		case protoreflect.EnumDescriptor:
			enumGenerator{pkg: p.pkg, enum: v}.Generate(f)
		case protoreflect.ServiceDescriptor:
			services = append(services, v)
			if err := (serviceGenerator{
				pkg:     p.pkg,
				service: v,
			}).Generate(f); err != nil {
				walkErr = err
				return false
			}
		}
		return true
	})
	if walkErr != nil {
		return walkErr
	}
	// Generate the unified ApiClient after all individual service clients.
	generateApiClient(f, services)
	return nil
}

func (p packageGenerator) generateHeader(f *codegen.File) {
	f.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	f.P("/* eslint-disable no-use-before-define, @typescript-eslint/no-unused-vars, prettier/prettier */")
	f.P("// @ts-nocheck: generated code does not require type checking")
	f.P()
}
